[tool.poetry]
name = "book-review-platform"
version = "0.1.0"
description = "The collaborative hub for literary enthusiasts"
authors = []
license = "Unlicense"
readme = "README.md"
packages = [{ include = "book_review" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.0"
aiohttp = {extras = ["speedups"], version = "^3.9.5"}
mypy = "^1.9.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.7"

[tool.poetry.scripts]
serve = "book_review.main:main"
format = "tools:format"
lint = "tools:lint"
typecheck = "tools:typecheck"

[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
